# Generated by Django 2.1.4 on 2018-12-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rate_average',
            field=models.IntegerField(default=0, verbose_name='평점'),
        ),
    ]
