# Generated by Django 2.1.4 on 2018-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
    ]
