# Generated by Django 2.1.3 on 2018-11-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wannago',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
