# Generated by Django 2.1.4 on 2018-12-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address_detail',
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuimage_res', to='restaurants.Restaurant', verbose_name='메뉴이미지'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=250, verbose_name='주소'),
        ),
    ]
