# Generated by Django 2.1.3 on 2018-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuImages',
            new_name='MenuImage',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, verbose_name='유튜브'),
        ),
    ]
