# Generated by Django 2.1.4 on 2018-12-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181207_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['pk'], 'verbose_name': '음식점', 'verbose_name_plural': '음식점 목록'},
        ),
    ]
