# Generated by Django 2.1.4 on 2018-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181205_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_text',
            field=models.TextField(blank=True, verbose_name='메뉴텍스트'),
        ),
    ]
