# Generated by Django 2.1.3 on 2018-12-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181205_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rate_average',
            field=models.IntegerField(blank=True, default=3, verbose_name='평점'),
            preserve_default=False,
        ),
    ]
