# Generated by Django 2.1.4 on 2018-12-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rate_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='평점'),
        ),
    ]
