# Generated by Django 2.1.4 on 2018-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181210_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rate_bad',
            field=models.IntegerField(default=0, verbose_name='별로'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rate_good',
            field=models.IntegerField(default=0, verbose_name='맛있다'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rate_normal',
            field=models.IntegerField(default=0, verbose_name='괜찮다'),
        ),
    ]
