# Generated by Django 2.1.4 on 2018-12-14 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181210_1711'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_users',
            field=models.ManyToManyField(related_name='wannago_posts', related_query_name='wannago_post', through='restaurants.Wannago', to=settings.AUTH_USER_MODEL),
        ),
    ]
