# Generated by Django 2.1.3 on 2018-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181126_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='전화번호'),
        ),
    ]
