# Generated by Django 2.1.4 on 2018-12-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatdeal',
            name='description',
            field=models.TextField(default='', max_length=225, verbose_name='설명'),
            preserve_default=False,
        ),
    ]
