# Generated by Django 2.1.3 on 2018-11-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181130_2118'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.AddField(
            model_name='post',
            name='Restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='음식점'),
            preserve_default=False,
        ),
    ]
