# Generated by Django 2.1.3 on 2018-12-03 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181130_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Restaurant',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='음식점평가'),
        ),
    ]
